#!/bin/sh

FILENAME="$1"
ABIFILE = "$2"
export PATH="/data/bin:$PATH"
# chmod +x /data/bin/solc

dotnet /home/test/tools/Smartian/build/Smartian.dll fuzz -p "$FILENAME" -a "$ABIFILE" -t 20 -o /home/123